DESC CLASS_REQUEST;
DESC STUDENT;
DESC CLASS;

SELECT REQUEST_ID, STUDENT_NAME FROM CLASS_REQUEST INNER JOIN STUDENT USING(STUDENT_ID)
ORDER BY REQUEST_ID ASC;

SELECT REQUEST_ID, CLASS_NAME FROM CLASS_REQUEST INNER JOIN CLASS USING(CLASS_ID)
ORDER BY REQUEST_ID ASC;

SELECT REQUEST_ID, STUDENT_NAME, CLASS_NAME FROM CLASS_REQUEST INNER JOIN STUDENT USING(STUDENT_ID)
INNER JOIN CLASS USING(CLASS_ID)
ORDER BY REQUEST_ID ASC;

