DESC FRONT_VERSION_HIST;
DESC BACK_VERSION_HIST;

SELECT FRONT_VERSION_HIST.version_id, version_content_front, version_content_back FROM FRONT_VERSION_HIST LEFT OUTER JOIN BACK_VERSION_HIST ON FRONT_VERSION_HIST.version_id = BACK_VERSION_HIST.version_id ORDER BY version_id ASC;

SELECT BACK_VERSION_HIST.version_id, version_content_front, version_content_back FROM FRONT_VERSION_HIST RIGHT OUTER JOIN BACK_VERSION_HIST ON FRONT_VERSION_HIST.version_id = BACK_VERSION_HIST.version_id ORDER BY version_id ASC;

SELECT FRONT_VERSION_HIST.version_id, version_content_front, version_content_back FROM FRONT_VERSION_HIST LEFT OUTER JOIN BACK_VERSION_HIST ON FRONT_VERSION_HIST.version_id = BACK_VERSION_HIST.version_id UNION SELECT BACK_VERSION_HIST.version_id, version_content_front, version_content_back FROM FRONT_VERSION_HIST RIGHT OUTER JOIN BACK_VERSION_HIST ON FRONT_VERSION_HIST.version_id = BACK_VERSION_HIST.version_id ORDER BY version_id ASC;

