SELECT PRODUCT_NAME FROM COMMERCE_A WHERE PRODUCT_STOCK > 0
UNION
SELECT PRODUCT_NAME FROM COMMERCE_B WHERE PRODUCT_STOCK > 0
ORDER BY PRODUCT_NAME ASC;

SELECT PRODUCT_NAME FROM COMMERCE_A WHERE PRODUCT_STOCK > 0
INTERSECT
SELECT PRODUCT_NAME FROM COMMERCE_B WHERE PRODUCT_STOCK > 0
ORDER BY PRODUCT_NAME ASC;
