DESC STUDENT;
DESC COURSE_SCORE;

SELECT C.COURSE_NAME, S.DEPARTMENT, AVG(C.SCORE) AS AVERAGE_SCORE FROM COURSE_SCORE C INNER JOIN STUDENT S ON C.STUDENT_ID = S.ID GROUP BY C.COURSE_NAME, S.DEPARTMENT WITH ROLLUP;