DESC STUDENT;

SELECT ID,SCORE,CUME_DIST() OVER(ORDER BY SCORE DESC) AS CUME_DIST FROM STUDENT ORDER BY ID;
 
SELECT ID,SCORE, CUME_DIST FROM (SELECT ID,SCORE,CUME_DIST() OVER(ORDER BY SCORE DESC) AS CUME_DIST FROM STUDENT) s WHERE CUME_DIST>0.3 AND CUME_DIST<=0.7 ORDER BY CUME_DIST;