DESC PRODUCT;
DESC SELL;
SELECT * FROM PRODUCT;
SELECT * FROM SELL;

SELECT SELL_ID, SELLER_NAME, PRODUCT_NAME, QUANTITY FROM SELL INNER JOIN PRODUCT ON (SELL.PRODUCT_ID = PRODUCT.PRODUCT_ID) ORDER BY SELL_ID ASC;

SELECT SELL_ID, SELLER_NAME, PRODUCT_NAME, QUANTITY, SUM
(PRICE * QUANTITY) OVER 
(PARTITION BY SELLER_NAME, SELL.PRODUCT_ID) AS SUM_PRICE FROM SELL INNER JOIN PRODUCT ON (SELL.PRODUCT_ID = PRODUCT.PRODUCT_ID) 
ORDER BY SELL_ID ASC;
