DESC PARTICIPANT;

SELECT ID, GROUP_NUM, TIME_RECORD, 
    LAG(TIME_RECORD, 1) 
    OVER(PARTITION BY GROUP_NUM ORDER BY TIME_RECORD ASC) 
AS LAG, 
    LEAD(TIME_RECORD, 1) 
    OVER(PARTITION BY GROUP_NUM ORDER BY TIME_RECORD ASC) 
AS LEAD, 
    FIRST_VALUE(TIME_RECORD) 
    OVER(PARTITION BY GROUP_NUM ORDER BY TIME_RECORD ASC ROWS 
    BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
    AS FIRST_VALUE,     
    LAST_VALUE(TIME_RECORD) 
    OVER(PARTITION BY GROUP_NUM ORDER BY TIME_RECORD ASC ROWS 
    BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING)
    AS LAST_VALUE 
FROM PARTICIPANT
ORDER BY GROUP_NUM ASC, TIME_RECORD ASC;